from db import *
#add_dot('1','Кнопка "Информационный режим"','Информационный режим')
#add_user('1','student_bach','180','1')
#add_speciality('1','3','4')
#add_exam('1','1','Физика','40')
#add_achievement('1','1','Значок ГТО','3')
#update_user_ege_points ('181','1')
#update_exam_points ('41','1')
#delete_exam ('Физика', '1')
#delete_achievement ('Значок ГТО', '1')
#add_dot('2','Кнопка "Интерактивный режим"','Интерактивный режим')
#add_dot('3','Кнопка "Абитуриентам"','Абитуриентам')
#add_speciality('3','Приборостроение','178')