from db import *
#add_dot('1','Кнопка "Информационный режим"','Информационный режим')
#add_user('1','student_bach','180','1')
#add_speciality('1','3','4')
#add_exam('1','1','Физика','40')
#add_achievement('1','1','Значок ГТО','3')
#update_user_ege_points ('181','1')
#update_exam_points ('41','1')
#delete_exam ('Физика', '1')
#delete_achievement ('Значок ГТО', '1')
#add_dot('2','Кнопка "Интерактивный режим"','Интерактивный режим')
#add_dot('3','Кнопка "Абитуриентам"','Абитуриентам')
#add_speciality('1','Программная инженерия','235')
#add_speciality('2','Информатика и вычислительная техника','204')
#add_speciality('3','Приборостроение','178')
#add_speciality('4','Физика','175')
#add_user('2','school_grad','200','2')
#add_exam('1','2','Профильная математика','70')
#add_exam('2','2','Физика','50')
#add_exam('3','2','Русский язык','80')
#add_achievement('1','2','Золотой значок ГТО','3')
#add_user('3','school_grad','190','3')
#delete_user ('181', '1')
#add_user('1','school_grad','230','1')
#delete_user ('230', '1')
#delete_user ('200', '2')
#delete_user ('190', '3')
#add_user('1','school_grad','190','10','0')
#add_user('2','school_grad','200','2121','2117')
#add_user('3','school_grad','230','2151','2141')
#update_user_ege_points ('203','2')